#!/usr/bin/env python
"""Aggregate a long-window diabetes carrier graph.

This script aggregates the raw selected long-window carrier graph generated by:

    scripts/25_build_long_window_diabetes_carrier_graph.py

Default input:

    data/processed/diabetes_2000_2024_v1_carrier_graph/

Default output:

    data/processed/diabetes_2000_2024_v1_carrier_graph_aggregated/

What this script does
---------------------
1. Deduplicates node tables:
   - nodes_paper.parquet by PMID
   - nodes_patent.parquet by PatentId
   - nodes_clinicaltrial.parquet by nct_id
   - nodes_project.parquet by ProjectNumber
   - nodes_bioentity.parquet by EntityId

2. Aggregates carrier-BioEntity mention edges:
   - edges_paper_bioentity.parquet by PMID + EntityId + Type + year
   - edges_patent_bioentity.parquet by PatentId + EntityId + Type + year
   - edges_trial_bioentity.parquet by nct_id + EntityId + Type + year

   Main added columns:
   - mention_count
   - distinct_mention_count
   - sample_mention
   - mention_types
   - text_fields
   - avg_prob
   - max_prob
   - evidence flags

3. Deduplicates context edges:
   - edges_patent_paper.parquet by PatentId + PMID
   - edges_paper_trial.parquet by PMID + nct_id
   - edges_paper_project.parquet by PMID + ProjectNumber
   - edges_patent_project.parquet by PatentId + ProjectNumber
   - edges_trial_project.parquet by nct_id + ProjectNumber

4. Writes:
   - aggregation_summary.json
   - graph_summary.json
   - aggregation_report.md
   - graph_manifest.csv
   - aggregation_manifest.csv

Typical run
-----------
python scripts/25b_aggregate_long_window_carrier_graph.py \
  --input-dir data/processed/diabetes_2000_2024_v1_carrier_graph \
  --output-dir data/processed/diabetes_2000_2024_v1_carrier_graph_aggregated \
  --threads 4 \
  --memory-limit 24GB \
  --overwrite
"""

from __future__ import annotations

import argparse
import csv
import json
import shutil
import sys
import time
from pathlib import Path
from typing import Any


NODE_FILES = {
    "nodes_paper": {
        "file_name": "nodes_paper.parquet",
        "id_column": "PMID",
        "description": "Deduplicated paper nodes.",
    },
    "nodes_patent": {
        "file_name": "nodes_patent.parquet",
        "id_column": "PatentId",
        "description": "Deduplicated patent nodes.",
    },
    "nodes_clinicaltrial": {
        "file_name": "nodes_clinicaltrial.parquet",
        "id_column": "nct_id",
        "description": "Deduplicated clinical trial nodes.",
    },
    "nodes_project": {
        "file_name": "nodes_project.parquet",
        "id_column": "ProjectNumber",
        "description": "Deduplicated project nodes.",
    },
    "nodes_bioentity": {
        "file_name": "nodes_bioentity.parquet",
        "id_column": "EntityId",
        "description": "Deduplicated BioEntity nodes.",
    },
}

BIOENTITY_EDGE_FILES = {
    "edges_paper_bioentity": {
        "file_name": "edges_paper_bioentity.parquet",
        "carrier_id_column": "PMID",
        "carrier_type": "paper",
        "node_table": "nodes_paper",
        "description": "Aggregated Paper-BioEntity mention edges.",
    },
    "edges_patent_bioentity": {
        "file_name": "edges_patent_bioentity.parquet",
        "carrier_id_column": "PatentId",
        "carrier_type": "patent",
        "node_table": "nodes_patent",
        "description": "Aggregated Patent-BioEntity mention edges.",
    },
    "edges_trial_bioentity": {
        "file_name": "edges_trial_bioentity.parquet",
        "carrier_id_column": "nct_id",
        "carrier_type": "trial",
        "node_table": "nodes_clinicaltrial",
        "description": "Aggregated ClinicalTrial-BioEntity mention edges.",
    },
}

CONTEXT_EDGE_FILES = {
    "edges_patent_paper": {
        "file_name": "edges_patent_paper.parquet",
        "key_columns": ["PatentId", "PMID"],
        "description": "Deduplicated Patent-Paper context edges.",
    },
    "edges_paper_trial": {
        "file_name": "edges_paper_trial.parquet",
        "key_columns": ["PMID", "nct_id"],
        "description": "Deduplicated Paper-ClinicalTrial context edges.",
    },
    "edges_paper_project": {
        "file_name": "edges_paper_project.parquet",
        "key_columns": ["PMID", "ProjectNumber"],
        "description": "Deduplicated Paper-Project context edges.",
    },
    "edges_patent_project": {
        "file_name": "edges_patent_project.parquet",
        "key_columns": ["PatentId", "ProjectNumber"],
        "description": "Deduplicated Patent-Project context edges.",
    },
    "edges_trial_project": {
        "file_name": "edges_trial_project.parquet",
        "key_columns": ["nct_id", "ProjectNumber"],
        "description": "Deduplicated ClinicalTrial-Project context edges.",
    },
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Aggregate long-window diabetes carrier graph."
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=Path("data/processed/diabetes_2000_2024_v1_carrier_graph"),
        help="Input raw selected carrier graph directory.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("data/processed/diabetes_2000_2024_v1_carrier_graph_aggregated"),
        help="Output aggregated carrier graph directory.",
    )
    parser.add_argument("--threads", type=int, default=4)
    parser.add_argument("--memory-limit", default="24GB")
    parser.add_argument("--temp-dir", type=Path, default=Path("data/interim/duckdb_tmp"))
    parser.add_argument("--compression", default="zstd")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--no-progress", action="store_true")
    return parser.parse_args()


def log(message: str) -> None:
    print(message, flush=True)


def sql_literal(value: str | Path) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def qident(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def scan_sql(path: Path) -> str:
    return f"read_parquet({sql_literal(path)})"


def connect_duckdb(args: argparse.Namespace):
    import duckdb

    args.temp_dir.mkdir(parents=True, exist_ok=True)

    connection = duckdb.connect()
    connection.execute("SET preserve_insertion_order=false")
    connection.execute(f"SET threads={int(args.threads)}")
    connection.execute(f"SET memory_limit={sql_literal(args.memory_limit)}")
    connection.execute(f"SET temp_directory={sql_literal(args.temp_dir)}")
    return connection


def execute(connection: Any, sql: str) -> None:
    connection.execute(sql)


def fetchone_int(connection: Any, sql: str) -> int:
    value = connection.execute(sql).fetchone()[0]
    return int(value)


def count_table(connection: Any, table_name: str) -> int:
    return fetchone_int(connection, f"SELECT COUNT(*) FROM {qident(table_name)}")


def get_columns(connection: Any, table_name: str) -> set[str]:
    rows = connection.execute(
        f"DESCRIBE SELECT * FROM {qident(table_name)}"
    ).fetchall()
    return {str(row[0]) for row in rows}


def require_files(input_dir: Path) -> None:
    required = []
    required.extend(meta["file_name"] for meta in NODE_FILES.values())
    required.extend(meta["file_name"] for meta in BIOENTITY_EDGE_FILES.values())
    required.extend(meta["file_name"] for meta in CONTEXT_EDGE_FILES.values())

    missing = [str(input_dir / file_name) for file_name in required if not (input_dir / file_name).exists()]

    if missing:
        raise FileNotFoundError(
            "Missing required input graph files:\n" + "\n".join(missing)
        )


def prepare_output_dir(output_dir: Path, overwrite: bool) -> None:
    if output_dir.exists() and any(output_dir.iterdir()):
        if not overwrite:
            raise FileExistsError(
                f"Output directory exists and is not empty: {output_dir}. "
                "Use --overwrite."
            )
        shutil.rmtree(output_dir)

    output_dir.mkdir(parents=True, exist_ok=True)


def run_step(args: argparse.Namespace, index: int, total: int, label: str, fn) -> Any:
    if not args.no_progress:
        log(f"[{index}/{total}] {label} ...")

    start = time.time()
    result = fn()
    elapsed = time.time() - start

    if not args.no_progress:
        log(f"[{index}/{total}] {label} done in {elapsed:.1f}s")

    return result


def copy_table_to_parquet(
    connection: Any,
    table_name: str,
    path: Path,
    compression: str,
) -> None:
    compression_sql = compression.upper()
    execute(
        connection,
        f"""
        COPY (
            SELECT * FROM {qident(table_name)}
        )
        TO {sql_literal(path)}
        (FORMAT PARQUET, COMPRESSION {compression_sql})
        """,
    )


def write_csv(path: Path, rows: list[dict[str, Any]], columns: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8", newline="") as output_file:
        writer = csv.DictWriter(output_file, fieldnames=columns)
        writer.writeheader()
        writer.writerows(rows)


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as output_file:
        json.dump(data, output_file, ensure_ascii=False, indent=2)


def markdown_table(rows: list[dict[str, Any]], columns: list[str]) -> str:
    if not rows:
        return "_No rows._\n"

    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]

    for row in rows:
        values = [
            str(row.get(column, ""))
            .replace("|", "\\|")
            .replace("\n", " ")
            for column in columns
        ]
        lines.append("| " + " | ".join(values) + " |")

    return "\n".join(lines) + "\n"


def create_input_views(connection: Any, input_dir: Path) -> None:
    for table_name, meta in NODE_FILES.items():
        execute(
            connection,
            f"""
            CREATE OR REPLACE TEMP VIEW {qident("input_" + table_name)} AS
            SELECT * FROM {scan_sql(input_dir / meta["file_name"])}
            """,
        )

    for table_name, meta in BIOENTITY_EDGE_FILES.items():
        execute(
            connection,
            f"""
            CREATE OR REPLACE TEMP VIEW {qident("input_" + table_name)} AS
            SELECT * FROM {scan_sql(input_dir / meta["file_name"])}
            """,
        )

    for table_name, meta in CONTEXT_EDGE_FILES.items():
        execute(
            connection,
            f"""
            CREATE OR REPLACE TEMP VIEW {qident("input_" + table_name)} AS
            SELECT * FROM {scan_sql(input_dir / meta["file_name"])}
            """,
        )


def nonempty_key_expr(column: str, alias: str = "t") -> str:
    return f"NULLIF(TRIM(CAST({alias}.{qident(column)} AS VARCHAR)), '')"


def any_value_expr(columns: set[str], column: str, output_name: str | None = None, alias: str = "t") -> str:
    out = output_name or column
    if column in columns:
        return f"ANY_VALUE({alias}.{qident(column)}) AS {qident(out)}"
    return f"CAST(NULL AS VARCHAR) AS {qident(out)}"


def double_expr(columns: set[str], column: str, alias: str = "t") -> str:
    if column in columns:
        return f"TRY_CAST({alias}.{qident(column)} AS DOUBLE)"
    return "CAST(NULL AS DOUBLE)"


def bigint_expr(columns: set[str], column: str, alias: str = "t") -> str:
    if column in columns:
        return f"TRY_CAST({alias}.{qident(column)} AS BIGINT)"
    return "CAST(NULL AS BIGINT)"


def string_agg_distinct_expr(
    columns: set[str],
    column: str,
    output_name: str,
    alias: str = "t",
) -> str:
    if column in columns:
        value_expr = f"NULLIF(TRIM(CAST({alias}.{qident(column)} AS VARCHAR)), '')"
        return (
            f"STRING_AGG(DISTINCT {value_expr}, '|') "
            f"FILTER (WHERE {value_expr} IS NOT NULL) AS {qident(output_name)}"
        )
    return f"CAST(NULL AS VARCHAR) AS {qident(output_name)}"


def count_distinct_expr(
    columns: set[str],
    column: str,
    output_name: str,
    alias: str = "t",
) -> str:
    if column in columns:
        value_expr = f"NULLIF(TRIM(CAST({alias}.{qident(column)} AS VARCHAR)), '')"
        return f"COUNT(DISTINCT {value_expr}) AS {qident(output_name)}"
    return f"CAST(0 AS BIGINT) AS {qident(output_name)}"


def flag_expr(columns: set[str], column: str, output_name: str, alias: str = "t") -> str:
    if column in columns:
        value_expr = f"NULLIF(TRIM(CAST({alias}.{qident(column)} AS VARCHAR)), '')"
        return (
            f"MAX(CASE WHEN {value_expr} IS NOT NULL THEN 1 ELSE 0 END) "
            f"AS {qident(output_name)}"
        )
    return f"CAST(0 AS INTEGER) AS {qident(output_name)}"


def create_deduplicated_node_tables(connection: Any) -> list[dict[str, Any]]:
    stats: list[dict[str, Any]] = []

    for table_name, meta in NODE_FILES.items():
        input_table = "input_" + table_name
        id_col = str(meta["id_column"])

        raw_count = count_table(connection, input_table)

        columns = get_columns(connection, input_table)

        # Use an explicit alias because nonempty_key_expr(..., alias="t")
        # generates expressions like t."PMID".
        id_expr = nonempty_key_expr(id_col, alias="t")

        if "year" in columns:
            order_expr = "TRY_CAST(t.\"year\" AS BIGINT) NULLS LAST"
        else:
            order_expr = id_expr

        execute(
            connection,
            f"""
            CREATE TEMP TABLE {qident(table_name)} AS
            SELECT * EXCLUDE (__rn)
            FROM (
                SELECT
                    t.*,
                    ROW_NUMBER() OVER (
                        PARTITION BY {id_expr}
                        ORDER BY {order_expr}
                    ) AS __rn
                FROM {qident(input_table)} t
                WHERE {id_expr} IS NOT NULL
            )
            WHERE __rn = 1
            """,
        )

        output_count = count_table(connection, table_name)

        stats.append(
            {
                "table": table_name,
                "file_name": meta["file_name"],
                "id_column": id_col,
                "raw_rows": raw_count,
                "deduplicated_rows": output_count,
                "removed_rows": raw_count - output_count,
            }
        )

    return stats


def create_deduplicated_context_edge_table(
    connection: Any,
    *,
    input_table_name: str,
    output_table_name: str,
    key_columns: list[str],
) -> dict[str, Any]:
    input_table = "input_" + input_table_name
    columns = get_columns(connection, input_table)

    raw_count = count_table(connection, input_table)

    normalized_key_items = [
        f"{nonempty_key_expr(column, alias='t')} AS {qident(column)}"
        for column in key_columns
    ]

    key_predicates = [
        f"{nonempty_key_expr(column, alias='t')} IS NOT NULL"
        for column in key_columns
    ]

    # Keep non-key columns as aggregated metadata. Avoid SELECT *, because
    # SELECT normalized_key AS PMID, * can create duplicate column names and
    # make later references brittle.
    aggregate_exprs: list[str] = []

    for column in sorted(columns):
        if column in key_columns:
            continue

        if column == "RecordYear":
            aggregate_exprs.append(
                f"MIN(TRY_CAST(t.{qident(column)} AS BIGINT)) AS min_record_year"
            )
            aggregate_exprs.append(
                f"MAX(TRY_CAST(t.{qident(column)} AS BIGINT)) AS max_record_year"
            )
            aggregate_exprs.append(any_value_expr(columns, column, column, alias="t"))
        else:
            aggregate_exprs.append(any_value_expr(columns, column, column, alias="t"))

    select_items = [
        *normalized_key_items,
        "COUNT(*) AS edge_record_count",
        *aggregate_exprs,
    ]

    group_by_items = [
        nonempty_key_expr(column, alias="t")
        for column in key_columns
    ]

    execute(
        connection,
        f"""
        CREATE TEMP TABLE {qident(output_table_name)} AS
        SELECT
            {", ".join(select_items)}
        FROM {qident(input_table)} t
        WHERE {" AND ".join(key_predicates)}
        GROUP BY {", ".join(group_by_items)}
        """,
    )

    output_count = count_table(connection, output_table_name)

    return {
        "edge_table": output_table_name,
        "raw_edge_rows": raw_count,
        "deduplicated_edge_rows": output_count,
        "removed_duplicate_rows": raw_count - output_count,
        "key_columns": "|".join(key_columns),
    }


def create_deduplicated_context_edge_tables(connection: Any) -> list[dict[str, Any]]:
    stats: list[dict[str, Any]] = []

    for table_name, meta in CONTEXT_EDGE_FILES.items():
        stats.append(
            create_deduplicated_context_edge_table(
                connection,
                input_table_name=table_name,
                output_table_name=table_name,
                key_columns=list(meta["key_columns"]),
            )
        )

    return stats


def create_aggregated_bioentity_edge_table(
    connection: Any,
    *,
    input_table_name: str,
    output_table_name: str,
    carrier_id_column: str,
    carrier_type: str,
    node_table: str,
) -> dict[str, Any]:
    input_table = "input_" + input_table_name

    columns = get_columns(connection, input_table)
    raw_count = count_table(connection, input_table)

    carrier_expr = nonempty_key_expr(carrier_id_column, alias="e")
    entity_expr = nonempty_key_expr("EntityId", alias="e")

    # Entity Type can be noisy but is important for KU pair-type construction.
    # Keep Type in the grouping key.
    type_expr = (
        "NULLIF(TRIM(CAST(e.\"Type\" AS VARCHAR)), '')"
        if "Type" in columns
        else "CAST(NULL AS VARCHAR)"
    )

    # Carrier year is taken from deduplicated carrier node tables.
    # The long-window builder writes a canonical `year` column to carrier nodes.
    node_id_col = carrier_id_column

    mention_expr = any_value_expr(columns, "Mention", "sample_mention", alias="e")
    mention_type_expr = any_value_expr(columns, "Type", "sample_mention_type", alias="e")
    distinct_mention_expr = count_distinct_expr(columns, "Mention", "distinct_mention_count", alias="e")
    mention_types_expr = string_agg_distinct_expr(columns, "Type", "mention_types", alias="e")
    text_fields_expr = string_agg_distinct_expr(columns, "TextFrom", "text_fields", alias="e")

    min_start_expr = f"MIN({bigint_expr(columns, 'StartPosition', alias='e')}) AS min_start_position"
    max_end_expr = f"MAX({bigint_expr(columns, 'EndPosition', alias='e')}) AS max_end_position"
    avg_prob_expr = f"AVG({double_expr(columns, 'prob', alias='e')}) AS avg_prob"
    max_prob_expr = f"MAX({double_expr(columns, 'prob', alias='e')}) AS max_prob"

    has_neural_expr = flag_expr(columns, "is_neural_normalized", "has_neural_normalized", alias="e")
    has_mesh_expr = flag_expr(columns, "mesh", "has_mesh", alias="e")
    has_mim_expr = flag_expr(columns, "mim", "has_mim", alias="e")
    has_cl_expr = flag_expr(columns, "CL", "has_cl", alias="e")
    has_cellosaurus_expr = flag_expr(columns, "cellosaurus", "has_cellosaurus", alias="e")
    has_ncbitaxon_expr = flag_expr(columns, "NCBITaxon", "has_ncbitaxon", alias="e")
    has_ncbigene_expr = flag_expr(columns, "NCBIGene", "has_ncbigene", alias="e")
    has_chebi_expr = flag_expr(columns, "CHEBI", "has_chebi", alias="e")
    source_files_expr = string_agg_distinct_expr(columns, "FileName", "source_files", alias="e")

    execute(
        connection,
        f"""
        CREATE TEMP TABLE {qident(output_table_name)} AS
        WITH normalized AS (
            SELECT
                {carrier_expr} AS carrier_id,
                {entity_expr} AS EntityId,
                {type_expr} AS Type,
                n.year AS year,
                e.*
            FROM {qident(input_table)} e
            INNER JOIN {qident(node_table)} n
                ON {carrier_expr} = NULLIF(TRIM(CAST(n.{qident(node_id_col)} AS VARCHAR)), '')
            WHERE {carrier_expr} IS NOT NULL
              AND {entity_expr} IS NOT NULL
              AND n.year IS NOT NULL
        )
        SELECT
            carrier_id AS {qident(carrier_id_column)},
            EntityId,
            Type,
            year,
            {sql_literal(carrier_type)} AS carrier_type,
            'carrier_bioentity_year' AS aggregation_level,
            COUNT(*) AS mention_count,
            {distinct_mention_expr},
            {mention_expr},
            {mention_type_expr},
            {mention_types_expr},
            {text_fields_expr},
            {source_files_expr},
            {min_start_expr},
            {max_end_expr},
            {avg_prob_expr},
            {max_prob_expr},
            {has_neural_expr},
            {has_mesh_expr},
            {has_mim_expr},
            {has_cl_expr},
            {has_cellosaurus_expr},
            {has_ncbitaxon_expr},
            {has_ncbigene_expr},
            {has_chebi_expr}
        FROM normalized e
        GROUP BY
            carrier_id,
            EntityId,
            Type,
            year
        """,
    )

    output_count = count_table(connection, output_table_name)

    duplicate_rows_removed = raw_count - output_count
    compression_ratio = raw_count / output_count if output_count else None

    return {
        "edge_table": output_table_name,
        "carrier_type": carrier_type,
        "carrier_id_column": carrier_id_column,
        "raw_mention_edge_count": raw_count,
        "aggregated_edge_count": output_count,
        "removed_duplicate_rows": duplicate_rows_removed,
        "compression_ratio_raw_to_aggregated": f"{compression_ratio:.3f}" if compression_ratio else "",
    }


def create_aggregated_bioentity_edge_tables(connection: Any) -> list[dict[str, Any]]:
    stats: list[dict[str, Any]] = []

    for table_name, meta in BIOENTITY_EDGE_FILES.items():
        stats.append(
            create_aggregated_bioentity_edge_table(
                connection,
                input_table_name=table_name,
                output_table_name=table_name,
                carrier_id_column=str(meta["carrier_id_column"]),
                carrier_type=str(meta["carrier_type"]),
                node_table=str(meta["node_table"]),
            )
        )

    return stats


def count_outputs(connection: Any) -> dict[str, int]:
    output_names = [
        *NODE_FILES.keys(),
        *BIOENTITY_EDGE_FILES.keys(),
        *CONTEXT_EDGE_FILES.keys(),
    ]
    return {name: count_table(connection, name) for name in output_names}


def write_outputs(
    connection: Any,
    args: argparse.Namespace,
    counts: dict[str, int],
) -> list[dict[str, Any]]:
    manifest_rows: list[dict[str, Any]] = []

    for table_name, meta in NODE_FILES.items():
        path = args.output_dir / meta["file_name"]
        copy_table_to_parquet(connection, table_name, path, args.compression)
        manifest_rows.append(
            {
                "artifact_type": "node",
                "name": table_name,
                "path": str(path),
                "row_count": counts.get(table_name, ""),
                "description": meta["description"],
            }
        )

    for table_name, meta in BIOENTITY_EDGE_FILES.items():
        path = args.output_dir / meta["file_name"]
        copy_table_to_parquet(connection, table_name, path, args.compression)
        manifest_rows.append(
            {
                "artifact_type": "edge",
                "name": table_name,
                "path": str(path),
                "row_count": counts.get(table_name, ""),
                "description": meta["description"],
            }
        )

    for table_name, meta in CONTEXT_EDGE_FILES.items():
        path = args.output_dir / meta["file_name"]
        copy_table_to_parquet(connection, table_name, path, args.compression)
        manifest_rows.append(
            {
                "artifact_type": "edge",
                "name": table_name,
                "path": str(path),
                "row_count": counts.get(table_name, ""),
                "description": meta["description"],
            }
        )

    return manifest_rows


def build_graph_scale(counts: dict[str, int]) -> dict[str, int]:
    return {
        "paper_nodes": counts.get("nodes_paper", 0),
        "patent_nodes": counts.get("nodes_patent", 0),
        "trial_nodes": counts.get("nodes_clinicaltrial", 0),
        "project_nodes": counts.get("nodes_project", 0),
        "bioentity_nodes": counts.get("nodes_bioentity", 0),
        "paper_bioentity_edges": counts.get("edges_paper_bioentity", 0),
        "patent_bioentity_edges": counts.get("edges_patent_bioentity", 0),
        "trial_bioentity_edges": counts.get("edges_trial_bioentity", 0),
        "patent_paper_edges": counts.get("edges_patent_paper", 0),
        "paper_trial_edges": counts.get("edges_paper_trial", 0),
        "paper_project_edges": counts.get("edges_paper_project", 0),
        "patent_project_edges": counts.get("edges_patent_project", 0),
        "trial_project_edges": counts.get("edges_trial_project", 0),
    }


def write_manifest_files(
    output_dir: Path,
    manifest_rows: list[dict[str, Any]],
) -> None:
    columns = ["artifact_type", "name", "path", "row_count", "description"]

    aggregation_manifest = output_dir / "aggregation_manifest.csv"
    graph_manifest = output_dir / "graph_manifest.csv"

    manifest_plus_reports = list(manifest_rows)

    report_rows = [
        {
            "artifact_type": "report",
            "name": "aggregation_summary",
            "path": str(output_dir / "aggregation_summary.json"),
            "row_count": "",
            "description": "JSON summary of long-window graph aggregation.",
        },
        {
            "artifact_type": "report",
            "name": "graph_summary",
            "path": str(output_dir / "graph_summary.json"),
            "row_count": "",
            "description": "Compatibility JSON graph summary.",
        },
        {
            "artifact_type": "report",
            "name": "aggregation_report",
            "path": str(output_dir / "aggregation_report.md"),
            "row_count": "",
            "description": "Human-readable aggregation report.",
        },
        {
            "artifact_type": "report",
            "name": "aggregation_manifest",
            "path": str(aggregation_manifest),
            "row_count": len(manifest_rows) + 5,
            "description": "Manifest of aggregated graph artifacts.",
        },
        {
            "artifact_type": "report",
            "name": "graph_manifest",
            "path": str(graph_manifest),
            "row_count": len(manifest_rows) + 5,
            "description": "Compatibility manifest of aggregated graph artifacts.",
        },
    ]

    manifest_plus_reports.extend(report_rows)

    write_csv(aggregation_manifest, manifest_plus_reports, columns)
    write_csv(graph_manifest, manifest_plus_reports, columns)


def write_aggregation_stats(
    output_dir: Path,
    node_stats: list[dict[str, Any]],
    bioedge_stats: list[dict[str, Any]],
    context_edge_stats: list[dict[str, Any]],
) -> None:
    write_csv(
        output_dir / "node_deduplication_stats.csv",
        node_stats,
        [
            "table",
            "file_name",
            "id_column",
            "raw_rows",
            "deduplicated_rows",
            "removed_rows",
        ],
    )

    write_csv(
        output_dir / "bioentity_edge_aggregation_stats.csv",
        bioedge_stats,
        [
            "edge_table",
            "carrier_type",
            "carrier_id_column",
            "raw_mention_edge_count",
            "aggregated_edge_count",
            "removed_duplicate_rows",
            "compression_ratio_raw_to_aggregated",
        ],
    )

    write_csv(
        output_dir / "context_edge_deduplication_stats.csv",
        context_edge_stats,
        [
            "edge_table",
            "raw_edge_rows",
            "deduplicated_edge_rows",
            "removed_duplicate_rows",
            "key_columns",
        ],
    )


def write_report(
    output_dir: Path,
    args: argparse.Namespace,
    runtime_seconds: float,
    counts: dict[str, int],
    node_stats: list[dict[str, Any]],
    bioedge_stats: list[dict[str, Any]],
    context_edge_stats: list[dict[str, Any]],
    manifest_rows: list[dict[str, Any]],
) -> None:
    graph_scale = build_graph_scale(counts)

    parameter_rows = [
        {"parameter": "input_dir", "value": str(args.input_dir)},
        {"parameter": "output_dir", "value": str(args.output_dir)},
        {"parameter": "threads", "value": args.threads},
        {"parameter": "memory_limit", "value": args.memory_limit},
        {"parameter": "compression", "value": args.compression},
        {"parameter": "runtime_seconds", "value": f"{runtime_seconds:.1f}"},
    ]

    scale_rows = [{"metric": key, "count": value} for key, value in graph_scale.items()]

    parts = ["# Long-window Carrier Graph Aggregation Report\n"]

    parts.append("## 1. Parameters\n")
    parts.append(markdown_table(parameter_rows, ["parameter", "value"]))

    parts.append("\n## 2. Aggregation rule\n")
    parts.append(
        "Carrier-BioEntity mention edges are aggregated by "
        "`carrier_id + EntityId + Type + year`. The primary edge weight is "
        "`mention_count`. Carrier year is joined from the corresponding "
        "deduplicated carrier node table. Context edges are deduplicated by "
        "their endpoint key columns.\n"
    )

    parts.append("\n## 3. Final graph scale\n")
    parts.append(markdown_table(scale_rows, ["metric", "count"]))

    parts.append("\n## 4. Node deduplication stats\n")
    parts.append(
        markdown_table(
            node_stats,
            [
                "table",
                "id_column",
                "raw_rows",
                "deduplicated_rows",
                "removed_rows",
            ],
        )
    )

    parts.append("\n## 5. BioEntity edge aggregation stats\n")
    parts.append(
        markdown_table(
            bioedge_stats,
            [
                "edge_table",
                "carrier_type",
                "raw_mention_edge_count",
                "aggregated_edge_count",
                "removed_duplicate_rows",
                "compression_ratio_raw_to_aggregated",
            ],
        )
    )

    parts.append("\n## 6. Context edge deduplication stats\n")
    parts.append(
        markdown_table(
            context_edge_stats,
            [
                "edge_table",
                "raw_edge_rows",
                "deduplicated_edge_rows",
                "removed_duplicate_rows",
                "key_columns",
            ],
        )
    )

    parts.append("\n## 7. Output artifacts\n")
    parts.append(
        markdown_table(
            manifest_rows,
            ["artifact_type", "name", "path", "row_count", "description"],
        )
    )

    parts.append("\n## 8. Recommended next step\n")
    parts.append(
        "Use this aggregated graph as input to Stage 04/05 KU construction:\n\n"
        "```bash\n"
        "python scripts/20_build_knowledge_units.py \\\n"
        "  --graph-dir data/processed/diabetes_2000_2024_v1_carrier_graph_aggregated \\\n"
        "  --output-dir data/datasets/knowledge_units/diabetes_2000_2024_v1_translational \\\n"
        "  --exclude-bioentity-types species \\\n"
        "  --pair-types chemical-disease gene-disease chemical-gene \\\n"
        "  --min-carrier-count 3 \\\n"
        "  --max-entities-per-carrier 0 \\\n"
        "  --overwrite\n"
        "```\n"
    )

    report_text = "\n".join(parts)
    (output_dir / "aggregation_report.md").write_text(report_text, encoding="utf-8")


def write_summary_json(
    output_dir: Path,
    args: argparse.Namespace,
    runtime_seconds: float,
    counts: dict[str, int],
    node_stats: list[dict[str, Any]],
    bioedge_stats: list[dict[str, Any]],
    context_edge_stats: list[dict[str, Any]],
) -> None:
    summary = {
        "script": "scripts/25b_aggregate_long_window_carrier_graph.py",
        "command": " ".join(sys.argv),
        "input_dir": str(args.input_dir),
        "output_dir": str(args.output_dir),
        "threads": args.threads,
        "memory_limit": args.memory_limit,
        "compression": args.compression,
        "runtime_seconds": runtime_seconds,
        "aggregation_rule": {
            "bioentity_edges": "carrier_id + EntityId + Type + year",
            "context_edges": "endpoint key columns",
            "node_tables": "one row per primary ID",
        },
        "graph_scale": build_graph_scale(counts),
        "node_deduplication_stats": node_stats,
        "bioentity_edge_aggregation_stats": bioedge_stats,
        "context_edge_deduplication_stats": context_edge_stats,
    }

    write_json(output_dir / "aggregation_summary.json", summary)
    write_json(output_dir / "graph_summary.json", summary)


def print_summary(
    output_dir: Path,
    counts: dict[str, int],
    bioedge_stats: list[dict[str, Any]],
    context_edge_stats: list[dict[str, Any]],
) -> None:
    print()
    print("Long-window carrier graph aggregation complete")
    print(f"Output directory: {output_dir}")
    print()

    print("BioEntity edge aggregation stats:")
    for row in bioedge_stats:
        print(
            f"- {row['edge_table']}: "
            f"raw={row['raw_mention_edge_count']:,}, "
            f"aggregated={row['aggregated_edge_count']:,}, "
            f"compression={row['compression_ratio_raw_to_aggregated']}"
        )

    print()
    print("Context edge deduplication stats:")
    for row in context_edge_stats:
        print(
            f"- {row['edge_table']}: "
            f"raw={row['raw_edge_rows']:,}, "
            f"deduplicated={row['deduplicated_edge_rows']:,}"
        )

    print()
    print("Final counts:")
    for key, value in build_graph_scale(counts).items():
        print(f"- {key}: {value:,}")

    print()
    print(f"Report: {output_dir / 'aggregation_report.md'}")
    print(f"Manifest: {output_dir / 'graph_manifest.csv'}")
    print()


def main() -> None:
    args = parse_args()
    start_time = time.time()

    if args.threads < 1:
        raise ValueError("--threads must be >= 1")

    args.input_dir = args.input_dir.resolve()
    args.output_dir = args.output_dir.resolve()
    args.temp_dir = args.temp_dir.resolve()

    require_files(args.input_dir)
    prepare_output_dir(args.output_dir, args.overwrite)

    connection = connect_duckdb(args)

    run_step(
        args,
        1,
        8,
        "Creating input graph views",
        lambda: create_input_views(connection, args.input_dir),
    )

    node_stats = run_step(
        args,
        2,
        8,
        "Deduplicating node tables",
        lambda: create_deduplicated_node_tables(connection),
    )

    context_edge_stats = run_step(
        args,
        3,
        8,
        "Deduplicating context edge tables",
        lambda: create_deduplicated_context_edge_tables(connection),
    )

    bioedge_stats = run_step(
        args,
        4,
        8,
        "Aggregating BioEntity mention edge tables",
        lambda: create_aggregated_bioentity_edge_tables(connection),
    )

    counts = run_step(
        args,
        5,
        8,
        "Counting aggregated outputs",
        lambda: count_outputs(connection),
    )

    manifest_rows = run_step(
        args,
        6,
        8,
        "Writing Parquet outputs",
        lambda: write_outputs(connection, args, counts),
    )

    runtime_seconds = time.time() - start_time

    run_step(
        args,
        7,
        8,
        "Writing summaries and manifests",
        lambda: (
            write_aggregation_stats(
                args.output_dir,
                node_stats,
                bioedge_stats,
                context_edge_stats,
            ),
            write_summary_json(
                args.output_dir,
                args,
                runtime_seconds,
                counts,
                node_stats,
                bioedge_stats,
                context_edge_stats,
            ),
            write_manifest_files(args.output_dir, manifest_rows),
        ),
    )

    run_step(
        args,
        8,
        8,
        "Writing aggregation report",
        lambda: write_report(
            args.output_dir,
            args,
            runtime_seconds,
            counts,
            node_stats,
            bioedge_stats,
            context_edge_stats,
            manifest_rows,
        ),
    )

    print_summary(args.output_dir, counts, bioedge_stats, context_edge_stats)


if __name__ == "__main__":
    main()